FROM m3ngyang/pipeswitch:base

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install transformers==2.5.0

WORKDIR /workspace
RUN git clone --branch main https://github.com/netx-repo/PipeSwitch.git

ENV PYTHONPATH=/workspace/PipeSwitch

WORKDIR /workspace/PipeSwitch
RUN python scripts/environment/container_download_models.py

WORKDIR /workspace/PipeSwitch/pytorch_plugin
RUN bash overwrite.sh /workspace/pytorch/

WORKDIR /workspace/pytorch
ENV CMAKE_PREFIX_PATH=/opt/conda/
RUN python setup.py install

WORKDIR /workspace
