FROM m3ngyang/pipeswitch:base

WORKDIR /workspace

RUN pip install --upgrade pip
RUN pip install scipy
RUN pip install transformers==2.5.0

WORKDIR /workspace
RUN git clone --branch main https://github.com/netx-repo/PipeSwitch.git

ENV PYTHONPATH=/workspace/PipeSwitch

WORKDIR /workspace/PipeSwitch
RUN python scripts/environment/container_download_models.py

WORKDIR /workspace
